# Environment Configuration for Chainy
# This file defines different environment settings

[development]
environment = "dev"
region = "ap-northeast-1"
domain = "localhost:3000"
protocol = "http"
api_endpoint = "https://9qwxcajqf9.execute-api.ap-northeast-1.amazonaws.com"
google_redirect_uri = "http://localhost:3000"
log_level = "DEBUG"
enable_debugging = true
enable_cors_debug = true
cost_optimization = false

[production]
environment = "prod"
region = "ap-northeast-1"
domain = "chainy.luichu.dev"
protocol = "https"
api_endpoint = "https://9qwxcajqf9.execute-api.ap-northeast-1.amazonaws.com"
google_redirect_uri = "https://chainy.luichu.dev"
log_level = "ERROR"
enable_debugging = false
enable_cors_debug = false
cost_optimization = true

[staging]
environment = "staging"
region = "ap-northeast-1"
domain = "staging.chainy.luichu.dev"
protocol = "https"
api_endpoint = "https://staging-api.execute-api.ap-northeast-1.amazonaws.com"
google_redirect_uri = "https://staging.chainy.luichu.dev"
log_level = "INFO"
enable_debugging = true
enable_cors_debug = false
cost_optimization = true
